@url = http://localhost:8000/api

# get sensors list
GET {{url}}/sensors/

###

# add sensor
POST {{url}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Новый датчик для санузла"
}

###

# update sensor
PATCH {{url}}/sensors/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# add measurement
POST {{url}}/measurements/
Content-Type: application/json

{
  "sensor": 1,
  "temperature": 22.2
}

###

# get information for curret sensor
GET {{url}}/sensors/1/
