# Generated by Django 4.1.2 on 2023-01-23 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_alter_article_options_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
